[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo             = 'autozimu/LanguageClient-neovim'
rev              = 'next'
# プラグインのアップデート時に呼び出されるコールバック
hook_post_update = 'call hook#post_update#language_client_neovim#load()'
# プラグインが読み込まれる際に呼び出されるコールバック
hook_add         = 'call hook#add#language_client_neovim#load()'

#構文チェック
[[plugins]]
repo     = 'w0rp/ale'
# プラグイン読み込み時のコールバック
hook_add = '''
    call hook#add#ale#load()
    " シンボルカラムを表示したままにする
    " let g:ale_sign_column_always = 1
    " 保存時に整形してくれる
    let g:ale_fix_on_save = 1
    " 補完してくれる
    let g:ale_completion_enabled = 1
    " エラー行に表示するマーク
    let g:ale_sign_error = '⨉'
    let g:ale_sign_warning = '⚠'
    " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
    let g:ale_linters = {
        \   'c' : ['clangd'],
        \   'cpp' : ['clangd']
    \}
'''

[[plugins]]
repo             = 'Chiel92/vim-autoformat'
# プラグイン読み込み時のコールバック
hook_add         = 'call hook#add#vim_autoformat#load()'
# プラグインアップデート時のコールバック
hook_post_update = 'call hook#post_update#vim_autoformat#load()'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'suan/vim-instant-markdown'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'glacambre/firenvim'
#hook_post_update = '''
#  call firenvim#install(0)
#'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'
