[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'jiangmiao/auto-pairs'

#[[plugins]]
#repo = 'glacambre/firenvim'
#hook_add = '''
#  call firenvim#install(0)
#'''
